### ISSUE TITLE
可以不设置用户ID，而只给channels发送消息吗？

### ISSUE THREAD

**Issue by youngformax** [3377/rss2tg#3]
目前不设置用户ID无法启动bot

**Comment by 3377** [comment]
**当前设计的逻辑：**

- 系统设计为"用户+频道"的模式
- 用户被视为必需的配置项
- 频道被视为可选的附加功能
此机器人设计初衷就是想基于tg聚合感兴趣的内容，定期推送给自己。

**Comment by youngformax** [comment]
> **当前设计的逻辑：**
> 
> * 系统设计为"用户+频道"的模式
> * 用户被视为必需的配置项
> * 频道被视为可选的附加功能
>   此机器人设计初衷就是想基于tg聚合感兴趣的内容，定期推送给自己。

OK，明白了。
